name: CI — Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore API
        run: dotnet restore EventBookingApi/EventBookingApi.csproj

      - name: Restore Tests
        run: dotnet restore EventBookingApi.Tests/EventBookingApi.Tests.csproj

      - name: Build API
        run: dotnet build EventBookingApi/EventBookingApi.csproj --no-restore --configuration Release

      - name: Build Tests
        run: dotnet build EventBookingApi.Tests/EventBookingApi.Tests.csproj --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test EventBookingApi.Tests/EventBookingApi.Tests.csproj --no-build --configuration Release --verbosity normal
