name: CI — Build, Test & Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore API
        run: dotnet restore EventBookingApi/EventBookingApi.csproj

      - name: Restore Tests
        run: dotnet restore EventBookingApi.Tests/EventBookingApi.Tests.csproj

      - name: Build API
        run: dotnet build EventBookingApi/EventBookingApi.csproj --no-restore --configuration Release

      - name: Build Tests
        run: dotnet build EventBookingApi.Tests/EventBookingApi.Tests.csproj --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test EventBookingApi.Tests/EventBookingApi.Tests.csproj --no-build --configuration Release --verbosity normal

      - name: Publish API
        run: dotnet publish EventBookingApi/EventBookingApi.csproj -c Release -o ./publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'eventbooking-api'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ./publish
